baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Project'
theme = "PaperMod"
[params]
    author = "wangacet2005-cmd"
    disableSpecial1stPost = true
    homeInfoParams = false
[author]
    name = "wangacet2005-cmd"
[caches]
  [caches.images]
    dir = ':cacheDir/images'